services:
  db_identity:
    container_name: db_identity
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5434:5434
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: identity
      PGDATA: /data/postgres
    volumes:
      - db_identity:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d identity" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

#  app:
#    networks:
#      - flash_card
#

volumes:
  db_identity:
  cache:
    driver: local