services:
  db_identity:
    container_name: db_identity
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: identity
      PGDATA: /data/postgres/db_identity
    volumes:
      - db_identity:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d identity" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#  cache:
#    image: redis:7.4.4
#    restart: always
#    ports:
#      - '6379:6379'
#    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#    volumes:
#      - cache:/data
  cache:
    image: redislabs/redisearch:latest
    restart: always
    ports:
      - '6379:6379'
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#    volumes:
#      - cache:/data

volumes:
  db_identity:
#  cache:
#    driver: local